const CACHE_VERSION = 'ghid-rta-static-v28-market-hydration';
const OFFLINE_URL = '/offline.html';
const SAFE_PAGES = [OFFLINE_URL,'/ghid-rta-mtl.html','/sarme-rta-builduri.html','/builduri-mtl-sarme-rta.html','/airflow-camera-rta-mtl.html','/control-temperatura-mtl.html','/diagnostic-gust-rta-mtl.html','/calculator-lichide-vape.html','/legislativ-vape.html'];
const STATIC_ASSETS = ['/assets/favicon-192.png','/assets/favicon-512.png','/assets/apple-touch-icon.png','/assets/smokee-logo-official.png','/assets/rta-hero-background.png','/assets/seo-pages.css','/assets/enhancements.css?v=7','/assets/enhancements.js?v=7','/assets/enhancements-core.js?v=8','/assets/market-2026.js?v=4','/assets/market-loading-guard.js?v=8','/assets/market-ui-recovery.js?v=2','/assets/market-2026-report.js?v=1','/assets/market-coverage-ui.js?v=2','/assets/market-sales-ui.js?v=3','/assets/market-sales-retailer-ui.js?v=2','/assets/market-sales-explorer.js?v=1','/assets/market-sales-explorer.css?v=1','/assets/market-management-v2.js?v=3','/assets/market-management.css?v=1','/assets/market-executive-report-v2.js?v=1','/assets/market-executive-report.css?v=1','/assets/market-demand-ui.js?v=1','/assets/market-demand-ui.css?v=1','/assets/market-hype-ui.js?v=2','/assets/market-hype-ui.css?v=2','/assets/market-management-augment.js?v=1','/assets/market-management-augment.css?v=1','/assets/market-view-switcher.js?v=3','/assets/market-view-switcher.css?v=3','/site.webmanifest','/site-en.webmanifest'];
self.addEventListener('install',event=>{event.waitUntil(caches.open(CACHE_VERSION).then(cache=>cache.addAll(SAFE_PAGES.concat(STATIC_ASSETS))).then(()=>self.skipWaiting()))});
self.addEventListener('activate',event=>{event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(key=>key!==CACHE_VERSION).map(key=>caches.delete(key)))).then(()=>self.clients.claim()))});
self.addEventListener('message',event=>{if(event.data&&event.data.type==='SKIP_WAITING')self.skipWaiting()});
async function networkFirst(request,fallback){try{const response=await fetch(request);if(response&&response.ok&&SAFE_PAGES.includes(new URL(request.url).pathname)){const cache=await caches.open(CACHE_VERSION);cache.put(request,response.clone())}return response}catch(error){return (await caches.match(request))||(await caches.match(fallback))}}
async function networkFirstData(request){try{const response=await fetch(request,{cache:'no-store'});if(response&&response.ok){const cache=await caches.open(CACHE_VERSION);cache.put(request,response.clone())}return response}catch(error){return caches.match(request)}}
self.addEventListener('fetch',event=>{const request=event.request;if(request.method!=='GET')return;const url=new URL(request.url);if(url.origin!==self.location.origin)return;if(request.mode==='navigate'){const safe=SAFE_PAGES.includes(url.pathname);event.respondWith(networkFirst(request,safe?url.pathname:OFFLINE_URL));return}if(url.pathname==='/sync-status.json'||url.pathname==='/'||url.pathname==='/index.html'||url.pathname.startsWith('/en/')){event.respondWith(fetch(request,{cache:'no-store'}));return}if(['/data/youtube-reviews.js','/data/market-2026.json','/data/market-coverage-2026.json','/data/market-sales-2026.json','/data/market-management-2026.json','/data/market-universe-audit-2026.json','/data/market-external-intelligence-2026.json','/data/market-demand-intelligence-2026.json','/data/market-product-presence-2026.json','/data/market-hype-radar-2026.json','/data/smokee-mods.json'].includes(url.pathname)){event.respondWith(networkFirstData(request));return}if(url.pathname==='/assets/enhancements.js'||url.pathname.startsWith('/assets/market-')){event.respondWith(networkFirstData(request));return}if(url.pathname.startsWith('/assets/')||url.pathname==='/site.webmanifest'||url.pathname==='/site-en.webmanifest'){event.respondWith(caches.match(request).then(cached=>cached||fetch(request).then(response=>{if(!response||!response.ok)return response;const copy=response.clone();caches.open(CACHE_VERSION).then(cache=>cache.put(request,copy));return response})))}});
