const OWNER='andreiclim77-cell';
const REPO='rta';
const WORKFLOW='market-hype-2026-sync.yml';
const REF='main';
const REFRESH_PATH='/__market-hype-refresh';
const THROTTLE_MS=10*60*1000;
function json(payload,status=200,origin='https://ghid-rta.ro'){return new Response(JSON.stringify(payload),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store','access-control-allow-origin':origin,'access-control-allow-methods':'GET, POST, OPTIONS','access-control-allow-headers':'content-type','vary':'Origin'}})}
function allowedOrigin(request){const o=request.headers.get('origin')||'';return /^https:\/\/(?:www\.)?ghid-rta\.ro$/i.test(o)?o:'https://ghid-rta.ro'}
async function gh(env,path,opt={}){if(!env.GITHUB_TOKEN)throw new Error('Missing GITHUB_TOKEN');return fetch('https://api.github.com/repos/'+OWNER+'/'+REPO+path,{...opt,headers:{accept:'application/vnd.github+json',authorization:'Bearer '+env.GITHUB_TOKEN,'content-type':'application/json','user-agent':'ghid-rta-market-hype-refresh','x-github-api-version':'2022-11-28',...(opt.headers||{})}})}
async function active(env){const r=await gh(env,'/actions/workflows/'+WORKFLOW+'/runs?branch='+REF+'&per_page=6');if(!r.ok)return false;const j=await r.json();return(j.workflow_runs||[]).some(x=>x.status==='queued'||x.status==='in_progress')}
async function dispatch(env){const r=await gh(env,'/actions/workflows/'+WORKFLOW+'/dispatches',{method:'POST',body:JSON.stringify({ref:REF})});if(r.status!==204)throw new Error('GitHub dispatch '+r.status+' '+(await r.text()).slice(0,120));return true}
export default{async fetch(request,env){const url=new URL(request.url),origin=allowedOrigin(request);if(url.pathname!==REFRESH_PATH)return json({ok:false},404,origin);if(request.method==='OPTIONS')return new Response(null,{status:204,headers:{'access-control-allow-origin':origin,'access-control-allow-methods':'GET, POST, OPTIONS','access-control-allow-headers':'content-type','access-control-max-age':'86400','vary':'Origin'}});if(request.method==='GET')return json({ok:true,service:'market-hype-refresh',workflow:WORKFLOW,mode:'dispatch-only'},200,origin);if(request.method!=='POST'||!/^https:\/\/(?:www\.)?ghid-rta\.ro$/i.test(request.headers.get('origin')||''))return json({ok:false},404,origin);try{const key='market-hype-refresh:last',last=env.RTA_METRICS?Number(await env.RTA_METRICS.get(key)||0):0,now=Date.now();if(last&&now-last<THROTTLE_MS)return json({ok:true,accepted:true,action:'throttled-recent-dispatch'},202,origin);if(await active(env))return json({ok:true,accepted:true,action:'already-running'},202,origin);await dispatch(env);if(env.RTA_METRICS)await env.RTA_METRICS.put(key,String(now),{expirationTtl:3600});return json({ok:true,accepted:true,action:'dispatched'},202,origin)}catch(e){return json({ok:false,error:String(e&&e.message||e).slice(0,180)},503,origin)}}};
