const OWNER='andreiclim77-cell';
const REPO='rta';
const WORKFLOW='market-hype-2026-sync.yml';
const REF='main';
const REFRESH_PATH='/__market-hype-refresh';
const THROTTLE_MS=10*60*1000;
const KV_KEY='market-hype-refresh:last';
function json(payload,status=200,origin='https://ghid-rta.ro'){return new Response(JSON.stringify(payload),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store','access-control-allow-origin':origin,'access-control-allow-methods':'GET, POST, OPTIONS','access-control-allow-headers':'content-type','vary':'Origin'}})}
function allowedOrigin(request){const o=request.headers.get('origin')||'';return /^https:\/\/(?:www\.)?ghid-rta\.ro$/i.test(o)?o:'https://ghid-rta.ro'}
async function gh(env,path,opt={}){if(!env.GITHUB_TOKEN)throw new Error('Refresh service unavailable');return fetch('https://api.github.com/repos/'+OWNER+'/'+REPO+path,{...opt,headers:{accept:'application/vnd.github+json',authorization:'Bearer '+env.GITHUB_TOKEN,'content-type':'application/json','user-agent':'ghid-rta-market-hype-refresh','x-github-api-version':'2022-11-28',...(opt.headers||{})}})}
async function runs(env){const r=await gh(env,'/actions/workflows/'+WORKFLOW+'/runs?branch='+REF+'&per_page=8');if(!r.ok)throw new Error('Refresh status unavailable');const j=await r.json();return j.workflow_runs||[]}
async function active(env){return(await runs(env)).some(x=>x.status==='queued'||x.status==='in_progress')}
async function dispatch(env){const r=await gh(env,'/actions/workflows/'+WORKFLOW+'/dispatches',{method:'POST',body:JSON.stringify({ref:REF})});if(r.status!==204)throw new Error('Refresh could not start');return true}
function usefulStep(step){return step&&step.name&&!/^(Set up job|Complete job|Post )/i.test(step.name)}
function stageLabel(name){const n=String(name||'');if(/Checkout|Setup Node/i.test(n))return'Pregătesc verificarea';if(/Collect upstream|pre-announcement/i.test(n))return'Scanez ultimele 72h';if(/Validate Hype|truth rules/i.test(n))return'Validez semnalele';if(/Publish complete|snapshot/i.test(n))return'Public raportul complet';return n||'Actualizez Hype Radar'}
async function progressForRun(env,run){if(!run)return{state:'queued',progress:3,stage:'Pornesc reverificarea'};if(run.status==='completed'){if(run.conclusion==='success')return{state:'completed',progress:100,stage:'Reverificare finalizată'};return{state:'error',progress:100,stage:'Reverificarea s-a oprit'}}if(run.status==='queued')return{state:'queued',progress:5,stage:'Reverificarea este în coadă'};let jobs=[];try{const r=await gh(env,`/actions/runs/${run.id}/jobs?per_page=30`);if(r.ok){const j=await r.json();jobs=j.jobs||[]}}catch(_){}const steps=jobs.flatMap(job=>(job.steps||[]).filter(usefulStep));if(!steps.length)return{state:'running',progress:10,stage:'Scanez ultimele 72h'};let completed=0,inProgress=null;for(const s of steps){if(s.status==='completed')completed++;else if(s.status==='in_progress'&&!inProgress)inProgress=s}const fractional=completed+(inProgress?0.45:0),pct=Math.max(8,Math.min(97,Math.round(fractional/steps.length*100))),stage=stageLabel(inProgress&&inProgress.name||steps.find(x=>x.status!=='completed')&&steps.find(x=>x.status!=='completed').name);return{state:'running',progress:pct,stage}}
async function refreshStatus(env){const rs=await runs(env),last=env.RTA_METRICS?Number(await env.RTA_METRICS.get(KV_KEY)||0):0,threshold=last?last-120000:0;let run=rs.find(x=>x.status==='queued'||x.status==='in_progress')||null;if(!run&&threshold)run=rs.find(x=>Date.parse(x.created_at||0)>=threshold)||null;if(!run&&rs.length)run=rs[0];const p=await progressForRun(env,run);return{ok:true,kind:'hype-refresh',...p,runId:run?Number(run.id||0):0,updatedAt:run&&run.updated_at||new Date().toISOString()}}
export default{async fetch(request,env){const url=new URL(request.url),origin=allowedOrigin(request);if(url.pathname!==REFRESH_PATH)return json({ok:false},404,origin);if(request.method==='OPTIONS')return new Response(null,{status:204,headers:{'access-control-allow-origin':origin,'access-control-allow-methods':'GET, POST, OPTIONS','access-control-allow-headers':'content-type','access-control-max-age':'86400','vary':'Origin'}});if(request.method==='GET'){try{return json(await refreshStatus(env),200,origin)}catch(_){return json({ok:false,kind:'hype-refresh',state:'unavailable',progress:0,stage:'Status indisponibil'},503,origin)}}if(request.method!=='POST'||!/^https:\/\/(?:www\.)?ghid-rta\.ro$/i.test(request.headers.get('origin')||''))return json({ok:false},404,origin);try{const last=env.RTA_METRICS?Number(await env.RTA_METRICS.get(KV_KEY)||0):0,now=Date.now();if(last&&now-last<THROTTLE_MS)return json({ok:true,kind:'hype-refresh',accepted:true,action:'throttled-recent-dispatch'},202,origin);if(await active(env)){if(env.RTA_METRICS)await env.RTA_METRICS.put(KV_KEY,String(now),{expirationTtl:3600});return json({ok:true,kind:'hype-refresh',accepted:true,action:'already-running'},202,origin)}await dispatch(env);if(env.RTA_METRICS)await env.RTA_METRICS.put(KV_KEY,String(now),{expirationTtl:3600});return json({ok:true,kind:'hype-refresh',accepted:true,action:'dispatched'},202,origin)}catch(_){return json({ok:false,kind:'hype-refresh',error:'Reverificarea nu a putut porni.'},503,origin)}}};
