#!/usr/bin/env node
'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),Core=require('../../assets/market-top20-core.js');
const ROOT=path.resolve(__dirname,'../..'),CATALOG=path.join(ROOT,'data/google-pod-catalog.json');
const hash=s=>crypto.createHash('sha256').update(s).digest('hex'),need=(b,c)=>{if(!b)throw new Error(c)};
function atomic(file,value){fs.mkdirSync(path.dirname(file),{recursive:true});const tmp=file+'.tmp-'+process.pid;fs.writeFileSync(tmp,value,{mode:0o644});fs.renameSync(tmp,file)}
function parseDelimited(input,delimiter){const rows=[];let row=[],field='',quoted=false,closed=false;for(let i=0;i<input.length;i++){const c=input[i];if(quoted){if(c==='"'&&input[i+1]==='"'){field+='"';i++}else if(c==='"'){quoted=false;closed=true}else field+=c;continue}if(c==='"'&&!field&&!closed){quoted=true;continue}if(c===delimiter){row.push(field);field='';closed=false;continue}if(c==='\n'||c==='\r'){if(c==='\r'&&input[i+1]==='\n')i++;row.push(field);if(row.some(x=>x.trim()))rows.push(row);row=[];field='';closed=false;continue}need(!closed||/\s/.test(c),'MALFORMED_CSV_QUOTE');field+=c}need(!quoted,'UNCLOSED_CSV_QUOTE');row.push(field);if(row.some(x=>x.trim()))rows.push(row);return rows}
function parseCount(v,locale){v=String(v==null?'':v).trim();if(['','—','-','--'].includes(v))return null;if(/^\d+$/.test(v))return Core.count(v);const rx=locale==='ro-RO'?/^\d{1,3}(\.\d{3})+$/:/^\d{1,3}(,\d{3})+$/;need(rx.test(v),'UNSUPPORTED_SEARCH_VALUE_OR_RANGE');const n=Core.count(v.replace(/[.,]/g,''));need(n!==null,'SEARCH_VALUE_OVERFLOW');return n}
function columnMonth(v){const s=Core.canonical(v),year=(s.match(/\b20\d{2}\b/)||[])[0];if(!year)return null;const tokens=s.split(' '),names=[['jan','january','ian','ianuarie'],['feb','february','februarie'],['mar','march','martie'],['apr','april','aprilie'],['may','mai'],['jun','june','iun','iunie'],['jul','july','iul','iulie'],['aug','august'],['sep','sept','september','septembrie'],['oct','october','octombrie'],['nov','november','noiembrie'],['dec','december','decembrie']],i=names.findIndex(set=>tokens.some(t=>set.includes(t)));return i<0?null:year+'-'+String(i+1).padStart(2,'0')}
function importCsv(bytes,catalog,config){
 need(Buffer.isBuffer(bytes)&&bytes.length<=4000000,'CSV_TOO_LARGE');let content=bytes[0]===255&&bytes[1]===254?bytes.subarray(2).toString('utf16le'):bytes.toString('utf8').replace(/^\ufeff/,'');
 need(config&&['ro-RO','en-US'].includes(config.number_locale),'NUMBER_LOCALE_REQUIRED');need(config.country==='RO'&&config.network==='GOOGLE_SEARCH'&&config.language==='all'&&config.scope_confirmed===true,'EXPORT_SCOPE_MUST_BE_REVIEWED');
 let rows,headerIndex=-1,keywordColumn=-1;
 for(const d of ['\t',',',';']){let candidate;try{candidate=parseDelimited(content,d)}catch(e){continue}const index=candidate.findIndex(row=>row.some(c=>['keyword','cuvant cheie','cuvinte cheie'].includes(Core.canonical(c))));if(index>=0&&candidate[index].length>2){rows=candidate;headerIndex=index;keywordColumn=rows[index].findIndex(c=>['keyword','cuvant cheie','cuvinte cheie'].includes(Core.canonical(c)));break}}
 need(headerIndex>=0,'KEYWORD_PLANNER_HEADER_NOT_FOUND');const header=rows[headerIndex],monthCols=new Map();header.forEach((v,i)=>{const m=columnMonth(v);if(m){need(!monthCols.has(m),'DUPLICATE_MONTH_COLUMN');monthCols.set(m,i)}});
 need(Core.ym(config.start)&&Core.ym(config.end)&&Core.shift(config.start,11)===config.end,'TWELVE_FULL_MONTHS_REQUIRED');const months=Array.from({length:12},(_,i)=>Core.shift(config.start,i));for(const m of months)need(monthCols.has(m),'EXPORT_MONTH_MISSING_'+m);
 const aliases=Core.validateCatalog(catalog),seen=new Map(),results=[];
 for(const row of rows.slice(headerIndex+1)){const word=(row[keywordColumn]||'').trim();if(!aliases.has(Core.canonical(word)))continue;need(row.length===header.length,'CSV_COLUMN_COUNT');const values=months.map(m=>({year:Number(m.slice(0,4)),month:Core.MONTHS[Number(m.slice(5))-1],monthlySearches:parseCount(row[monthCols.get(m)],config.number_locale)})),key=Core.canonical(word),signature=JSON.stringify(values);if(seen.has(key)){need(seen.get(key)===signature,'CONFLICTING_CSV_DUPLICATE');continue}seen.set(key,signature);results.push({text:word,closeVariants:[],keywordMetrics:{monthlySearchVolumes:values}})}
 // CSV does not expose cross-keyword grouping: do not sum exported aliases.
 need(catalog.every(m=>m.keywords.length===1),'CSV_REQUIRES_ONE_QUERY_PER_MODEL');
 return{schema_version:2,source:{provider:Core.PROVIDER,method:'keyword_planner_csv',retrieved_at:config.retrieved_at,original_sha256:hash(bytes),original_filename:path.basename(config.filename||'keywords.csv'),reviewed_by:config.reviewed_by,scope_confirmed:true},request:{country:'RO',network:'GOOGLE_SEARCH',language:'all',period:{start:config.start,end:config.end}},catalog,results};
}
async function googlePost(url,body,headers,fetcher){for(let attempt=0;attempt<3;attempt++){const r=await fetcher(url,{method:'POST',headers,body:JSON.stringify(body),signal:AbortSignal.timeout(30000)});if((r.status===429||r.status>=500)&&attempt<2){await new Promise(resolve=>setTimeout(resolve,1000*2**attempt));continue}need(r.ok,'GOOGLE_HTTP_'+r.status);return{body:await r.json(),requestId:r.headers.get('request-id')}}}
const REQUIRED=['GOOGLE_ADS_DEVELOPER_TOKEN','GOOGLE_ADS_CLIENT_ID','GOOGLE_ADS_CLIENT_SECRET','GOOGLE_ADS_REFRESH_TOKEN','GOOGLE_ADS_CUSTOMER_ID'];
function configuration(env){return{configured:REQUIRED.every(k=>Boolean(env[k])),missing:REQUIRED.filter(k=>!env[k]),use_approved:env.GOOGLE_ADS_USE_APPROVED==='true'}}
async function collect(catalog,env,fetcher=fetch){
 const cfg=configuration(env);need(cfg.configured,'GOOGLE_SOURCE_NOT_CONFIGURED');need(cfg.use_approved,'SOURCE_USE_APPROVAL_REQUIRED');Core.validateCatalog(catalog);const keywords=catalog.flatMap(m=>m.keywords);need(keywords.length<=10000,'TOO_MANY_KEYWORDS');
 const customer=env.GOOGLE_ADS_CUSTOMER_ID.replace(/-/g,''),version=env.GOOGLE_ADS_API_VERSION||'v24';need(/^\d{10}$/.test(customer)&&/^v\d+$/.test(version),'INVALID_GOOGLE_CONFIG');
 const r=await fetcher('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:env.GOOGLE_ADS_CLIENT_ID,client_secret:env.GOOGLE_ADS_CLIENT_SECRET,refresh_token:env.GOOGLE_ADS_REFRESH_TOKEN,grant_type:'refresh_token'}),signal:AbortSignal.timeout(30000)});
 need(r.ok,'GOOGLE_OAUTH_FAILED');const token=await r.json();need(typeof token.access_token==='string','GOOGLE_OAUTH_NO_TOKEN');const headers={'Content-Type':'application/json',Authorization:'Bearer '+token.access_token,'developer-token':env.GOOGLE_ADS_DEVELOPER_TOKEN};
 if(env.GOOGLE_ADS_LOGIN_CUSTOMER_ID){const manager=env.GOOGLE_ADS_LOGIN_CUSTOMER_ID.replace(/-/g,'');need(/^\d{10}$/.test(manager),'INVALID_MANAGER_ID');headers['login-customer-id']=manager}
 const base='https://googleads.googleapis.com/'+version+'/customers/'+customer;
 const geo=await googlePost(base+'/googleAds:search',{query:"SELECT geo_target_constant.resource_name, geo_target_constant.country_code, geo_target_constant.target_type, geo_target_constant.status FROM geo_target_constant WHERE geo_target_constant.country_code = 'RO' AND geo_target_constant.target_type = 'Country'"},headers,fetcher);
 const matches=(geo.body.results||[]).map(x=>x.geoTargetConstant).filter(x=>x.countryCode==='RO'&&x.targetType==='Country'&&x.status==='ENABLED');need(matches.length===1,'ROMANIA_TARGET_NOT_CONFIRMED');
 const end=Core.shift(new Date().toISOString().slice(0,7),-1),start=Core.shift(end,-11),yearMonth=m=>({year:Number(m.slice(0,4)),month:Core.MONTHS[Number(m.slice(5))-1]});
 const request={keywords,geoTargetConstants:[matches[0].resourceName],keywordPlanNetwork:'GOOGLE_SEARCH',historicalMetricsOptions:{yearMonthRange:{start:yearMonth(start),end:yearMonth(end)}}},result=await googlePost(base+':generateKeywordHistoricalMetrics',request,headers,fetcher);
 return{schema_version:2,source:{provider:Core.PROVIDER,method:'google_ads_api',retrieved_at:new Date().toISOString(),request_id:result.requestId,api_version:version},request:{country:'RO',network:'GOOGLE_SEARCH',language:'all',period:{start,end},google_request:request,google_geo:matches[0]},catalog,results:result.body.results||[]};
}
function publish(bundle,root=ROOT){
 const result=Core.build(bundle);need(result.status==='ready','FEWER_THAN_20_MEASURED_MODELS');const target=path.join(root,'data/google-pod-top20-2026.json');
 if(fs.existsSync(target)){const old=JSON.parse(fs.readFileSync(target,'utf8'));need(!old.retrieved_at||old.retrieved_at<=bundle.source.retrieved_at,'OLDER_SNAPSHOT_REJECTED');need(!old.reference_month||old.reference_month<=result.month,'OLDER_REFERENCE_MONTH_REJECTED')}
 const raw=JSON.stringify(bundle,null,2)+'\n',sha=hash(raw),relative='/data/google-pod-evidence/'+sha+'.json';atomic(path.join(root,relative.slice(1)),raw);
 const manifest={schema_version:2,status:'ready',evidence_path:relative,evidence_sha256:sha,retrieved_at:bundle.source.retrieved_at,reference_month:result.month,coverage:result.coverage};Core.validateManifest(manifest);atomic(target,JSON.stringify(manifest,null,2)+'\n');return manifest;
}
async function main(){
 const argv=process.argv.slice(2),arg=k=>{const i=argv.indexOf(k);return i<0?null:argv[i+1]};if(argv.includes('--check-config')){console.log(JSON.stringify(configuration(process.env),null,2));return}
 const catalog=JSON.parse(fs.readFileSync(arg('--catalog')||CATALOG,'utf8')).models;if(argv.includes('--keywords')){Core.validateCatalog(catalog);process.stdout.write(catalog.flatMap(m=>m.keywords).join('\n')+'\n');return}
 let bundle;if(argv.includes('--collect'))bundle=await collect(catalog,process.env);else if(arg('--csv')){const file=arg('--csv');bundle=importCsv(fs.readFileSync(file),catalog,{filename:file,number_locale:arg('--number-locale'),start:arg('--start'),end:arg('--end'),retrieved_at:arg('--retrieved-at'),reviewed_by:arg('--reviewed-by'),country:'RO',network:'GOOGLE_SEARCH',language:'all',scope_confirmed:argv.includes('--confirm-ro-google-all')})}else if(arg('--bundle'))bundle=JSON.parse(fs.readFileSync(arg('--bundle'),'utf8'));else throw new Error('Use --check-config, --keywords, --collect, --csv FILE or --bundle FILE. See docs/TOP20_GOOGLE.md.');
 const result=Core.build(bundle);console.log(JSON.stringify({status:result.status,month:result.month,coverage:result.coverage},null,2));if(argv.includes('--write')){const manifest=publish(bundle);console.log('Published verified-integrity source snapshot '+manifest.evidence_sha256)}
}
if(require.main===module)main().catch(e=>{console.error('Top20: '+e.message);process.exitCode=1});module.exports={parseDelimited,parseCount,columnMonth,importCsv,configuration,collect,publish,hash};
